# Usa una imagen base de Python
FROM python:3.10-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de requerimientos e instala las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Copia tu script de Python
COPY geoproc_app/geoproc.py .

# Comando para ejecutar el script
CMD ["python", "geoproc.py"]